### ISSUE TITLE
Add debugging section to LuckyFlow guides

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#199] opened 2019-12-06 21:44 UTC
@jwoertink Could you post here with some rough examples of what your team is using for different systems (Linux, Mac): https://gitter.im/luckyframework/Lobby?at=5de8468d08d0c961b7f06d31. We could likely use this in the debugging guide

I'd also love to link to this when LuckyFlow has issues connecting: https://gitter.im/luckyframework/Lobby?at=5dea763855066245987bdd39

**Comment by jwoertink** [comment] 2019-12-06 22:08
We currently use the standard MBP running catalina, but also a Linux machine running some flavor of Arch. For the linux machine, he had set:

```
settings.browser_binary = "/usr/bin/google-chrome-stable"
```

When I saw that, I thought it was the chromedriver path, so I pointed mine to `which chromedriver`. It turned out that I actually needed this:

```
settings.browser_binary = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

Which is a little tricky to find at first on a Mac.

This option ended up just being a `settings.browser_binary = ENV["BROWSER_PATH"]` in the end 😅 
The error message I was getting was the missing key status which is a bug in the current selenium shard. It was also a false error since that wasn't really the issue. 

I think for the website guides, we can show stuff like "If you're on a Mac, your browser will be installed in your /Applications folder (e.g. Applications/Google Chrome.app/Contents/MacOS/Google Chrome) or for brave...".

**Comment by paulcsmith** [comment] 2019-12-06 22:14
I've never actually needed to set the browser-binary so what happens for you if you leave that off? Does it just not find one  at all, or does it use an incorrect one?

**Comment by jwoertink** [comment] 2019-12-06 22:21
It actually runs fine on both mac and linux without that option. The issue is on Linux, it will actually open the chrome browser up instead of doing headless. As where on mac it just runs headless. So you have to change that if you want headless on linux, or using Brave

**Closed as completed** 2020-10-01 16:12 UTC
